name: JavaFx Hello Todo

on:
  push:
    tags:
      - "v*" # Esto activará la acción solo cuando crees una etiqueta (tag) como v1.0

permissions:
  contents: write

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Obtener SDK de JavaFX
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.10/openjfx-21.0.10_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.10_linux-x64_bin-sdk.zip 

      - name: Compilar y Empaquetar
        run: |
          mkdir -p build
          javac --module-path javafx-sdk-21.0.10/lib --add-modules javafx.controls -d build/ src/dam/optativa/HelloWorldFx.java [cite: 22]
          jar --create --file=build/HelloWorldFx.jar --manifest=manifest/MANIFEST.MF -C build/ . [cite: 28]

      - name: Generar instalador DEB
        run: |
          jpackage --input build/ --name HelloWorldFx --main-jar HelloWorldFx.jar --main-class dam.optativa.HelloWorldFx --type deb --module-path javafx-sdk-21.0.10/lib --add-modules javafx.controls [cite: 35, 36, 37, 38, 39, 40]

      - name: Subir Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorldFx-deb
          path: "*.deb"

      - name: Crear Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.deb"